Feature/reload
igorkulman/iOSLocalizationEditor pull request #99
Opened 2022-06-23 14:53 UTC by PhiFry

Added a reload function by pressing (CMD + R) which is a common shortcut to refresh on Mac. Fixed a bug where the comment displayed in the key cell was randomized between available languages to use the Base language.

2022-06-23 15:18 UTC, igorkulman requested changes

2022-06-23 16:17 UTC, PhiFry commented on sources/LocalizationEditor/UI/ViewController.swift
> +    private var currentOpenFolderUrl: URL?
Good catch will fix when I have access to my computer 👍

2022-06-23 16:30 UTC, PhiFry commented on sources/LocalizationEditor/UI/WindowController.swift
> +        appDelegate.openFolderMenuItem.action = #selector(WindowController.openFolder(_:))
openFolder calls the same delegate method, the openAction was redundant. The reload delegate method was created to keep consistency.

2022-06-25 09:47 UTC, igorkulman approved these changes

2022-06-25 12:56 UTC, merged